/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表（meta 全字段 + 云端开关状态） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务元信息列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                key?: string;
                                name?: string;
                                url?: string;
                                sourceUrl?: (string | string[]) | null;
                                note?: string | null;
                                category?: string | null;
                                lastUpdated?: string | null;
                                deprecated?: boolean;
                                enabled?: boolean;
                                inFlight?: boolean;
                                wallet?: string | null;
                                timeoutSec?: number | null;
                                retry?: {
                                    /** @description 额外重试次数 */
                                    max?: number;
                                    /** @description 重试间隔（秒） */
                                    backoffSec?: number;
                                } | null;
                                captcha?: {
                                    /** @description 是否自动打码 */
                                    auto?: boolean;
                                    /** @description 单任务费用上限（点） */
                                    maxCost?: number;
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 任务开关（写云端 task_states，立即生效无需重启） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 任务全局唯一 key */
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        enabled: boolean;
                    };
                };
            };
            responses: {
                /** @description 开关已写入 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                key?: string;
                                enabled?: boolean;
                            };
                        };
                    };
                };
                /** @description enabled 非布尔值（业务码 40000） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 任务不存在（业务码 40401） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/tasks/{key}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动触发任务（可选指定单窗口） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 任务全局唯一 key */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 指定窗口 id（缺省跑全部启用窗口） */
                        bitbrowserId?: string;
                    };
                };
            };
            responses: {
                /** @description 入队成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                /** @enum {string} */
                                scope?: "single" | "all";
                            };
                        };
                    };
                };
                /** @description 任务或窗口不存在（业务码 40401/40402） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 任务已停用（业务码 40901） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公开只读设置（不含任何密钥）+ 数据源状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 非敏感配置项 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                bitbrowserApiBase?: string;
                                webPort?: number;
                                concurrency?: number;
                                circuitBreakerThreshold?: number;
                                probeUrl?: string;
                                version?: string;
                                datasource?: {
                                    available?: boolean;
                                    error?: string;
                                    path?: string;
                                    rows?: number;
                                    columns?: string[];
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasource/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重载数据源 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 重载后的数据源信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                available?: boolean;
                                rows?: number;
                                columns?: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取截图文件（path 传截图目录内相对路径，双层防护防目录穿越） */
        get: {
            parameters: {
                query: {
                    /** @description 截图目录内的相对路径 */
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 截图文件二进制流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                /** @description 截图不存在或路径越界（业务码 40403） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 窗口列表（含启用状态、熔断计数与打开状态） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 窗口列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                id?: number;
                                bitbrowserId?: string;
                                name?: string;
                                /** @description 0/1 开关 */
                                enabled?: number;
                                circuitBreakerCount?: number;
                                /** @description 是否已打开（open_windows 登记 + 比特浏览器 pid 实测） */
                                open?: boolean;
                                /** @description 比特客户端窗口备注 */
                                remark?: string | null;
                                /** @description 比特客户端排序号 */
                                seq?: number | null;
                                /** @description 最近探测 IP */
                                lastIp?: string | null;
                                /** @description 最近探测国家 */
                                lastCountry?: string | null;
                                /** @description 浏览器内核版本 */
                                coreVersion?: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 窗口开关（只更新显式传入的 enabled 字段） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 窗口内部 id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description 当前窗口记录快照（更新前的字段值） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                id?: number;
                                bitbrowserId?: string;
                                name?: string;
                                enabled?: number;
                                circuitBreakerCount?: number;
                            };
                        };
                    };
                };
                /** @description 窗口不存在（业务码 40402） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/profiles/{id}/breaker/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重置该窗口熔断计数 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 窗口内部 id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已重置 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                /** @description 窗口不存在（业务码 40402） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 打开窗口（已打开则直接复用；登记 open_windows 供跨进程复用） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 窗口内部 id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 打开完成（already=true 表示此前已在打开状态，未重新开窗） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                /** @description true=复用已开窗口；false=本次新开 */
                                already?: boolean;
                            };
                        };
                    };
                };
                /** @description 窗口不存在（业务码 40402） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关闭窗口并清除打开状态登记（未登记也会尝试关窗一次） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 窗口内部 id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已关闭 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                /** @description 窗口不存在（业务码 40402） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API 使用手册 markdown 原文（前端 react-markdown 渲染） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 手册内容 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                content?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 示例任务文件清单（白名单限定） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 示例清单 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                name?: string;
                                label?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/examples/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单个示例任务源码（白名单校验） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 示例文件名（如 example-checkin.ts） */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 示例源码 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                content?: string;
                            };
                        };
                    };
                };
                /** @description 示例不存在或不在白名单（业务码 40404） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 看板全部数据（统计/矩阵/窗口/打码成本） */
        get: {
            parameters: {
                query?: {
                    /** @description 查询日期 YYYY-MM-DD（缺省今天） */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 看板数据 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                /** Format: date */
                                date?: string;
                                stats?: {
                                    total?: number;
                                    success?: number;
                                    failed?: number;
                                    captchaFailed?: number;
                                    skipped?: number;
                                    running?: number;
                                    pending?: number;
                                };
                                runs?: {
                                    id?: number;
                                    profileId?: number;
                                    taskKey?: string;
                                    date?: string;
                                    /** @enum {string} */
                                    status?: "pending" | "running" | "success" | "failed" | "captcha_failed" | "skipped" | "retry_wait";
                                    attempts?: number;
                                    error?: string | null;
                                    screenshot?: string | null;
                                    startedAt?: string | null;
                                    finishedAt?: string | null;
                                    durationSec?: number | null;
                                    inFlight?: boolean;
                                    slot: number;
                                    profileName?: string;
                                }[];
                                profiles?: {
                                    id?: number;
                                    bitbrowserId?: string;
                                    name?: string;
                                    /** @description 0/1 开关 */
                                    enabled?: number;
                                    circuitBreakerCount?: number;
                                    /** @description 比特客户端窗口备注 */
                                    remark?: string | null;
                                    /** @description 比特客户端排序号 */
                                    seq?: number | null;
                                    /** @description 最近探测 IP */
                                    lastIp?: string | null;
                                    /** @description 最近探测国家 */
                                    lastCountry?: string | null;
                                    /** @description 浏览器内核版本 */
                                    coreVersion?: string | null;
                                }[];
                                captcha?: {
                                    count?: number;
                                    totalCost?: number;
                                };
                                profilesTotal?: number;
                                profilesEnabled?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/captcha/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 打码余额（未配置 clientKey 或查询失败时 configured=false） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 余额信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                configured?: boolean;
                                points?: number;
                                /** @description 1000 点 = ¥1 */
                                yuan?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bitbrowser/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 比特浏览器本地 API 连接测试（失败不抛错，返回 ok:false） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 连接状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                ok?: boolean;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bitbrowser/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拉取比特浏览器窗口列表并写入 profiles 表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 同步数量 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0 */
                            code?: number;
                            /** @example ok */
                            message?: string;
                            data?: {
                                /** @description 同步入库的窗口数 */
                                count?: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
