/** api 唯一出口：任务只从这里 import 能力函数 */
export { openPage, click, fill, pressKey, runJs } from './page'
export { elementState, getText, hasText } from './find'
export { waitFor, race, waitResponse } from './wait'
export type { Probe, WaitProbe, WaitOptions } from './wait'
export { loginWallet, signMessage, confirmTransaction } from './wallet'
export type { WalletType, WalletScenario, WalletIntent, LoginSpec, WalletActionOptions } from './wallet'
export { clickTurnstile } from './captcha'
export { askAi, answerQuiz } from './ai'
export { getAccount, uploadFile, takeScreenshot } from './data'
export { recordStep, getSteps } from './diag'
export type { StepRecord } from '../automation'
